name: Build and Push Docker Image

on:
  release:
    types: [published]  # Déclenchement lorsque vous créez une release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Se connecter au registre Docker de GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire la version du tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Construire l’image Docker
        run: |
          run: docker build -t ghcr.io/namethief/projet-docker:${{ env.VERSION }} | tr '[:upper:]' '[:lower:]' .

      - name: Pousser l’image vers GitHub Packages
        run: |
          docker push ghcr.io/namethief/projet-docker:${{ env.VERSION }}
